name: Build Python 3.2.5

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      fail-fast: false 
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libc6-dev wget perl 

      - name: Run all build scripts
        run: |
          chmod +x scripts/*.sh
          ./scripts/build-sysroot.sh
          ./scripts/smoke-test.sh

      - name: Package output
        run: |
          cd $HOME/sysroot
          sudo tar -cJf ${{ github.workspace }}/python-3.2.5-${{ matrix.os }}.tar.xz .

      - name: Upload binary
        uses: softprops/action-gh-release@v1
        with:
          files: python-3.2.5-${{ matrix.os }}.tar.xz
